### ISSUE TITLE
Build Failing on AWS

### ISSUE THREAD

**Issue by jackdarl** [bertho-zero/react-redux-universal-hot-example#242]
I am at a total loss here.

I used this repository to build a project. Life was a charm when I was running the code locally. But when I tried deploying it on an AWS instance, it started throwing some really strange errors. None of these errors happened when I was building the code locally. What's even more puzzling is that I had done a test build of the project about a month ago on the same AWS instance, and it ran without a hitch.

Out of curiosity, I cloned this project afresh and ran it both locally and on my instance. While the code compiled and ran flawlessly on my local machine, it gave me those same errors when I tried it on my instance. 

I can reproduce the errors if asked. They're too many and too confusing so I'm not posting them here right now. 

Here's some more info that may help. I am using Ubuntu 14.04LTS, node v5.0.0 and npm 4.5.0 on my local system. My AWS **t2.micro** instance runs Ubuntu 16.04LTS. I tried different node and npm versions on my instance, even deleted and created new instances, but all the problems still remained. (Why a **t2.micro** instance? because it comes with the free tier. )

It's been over three days now and I have been unable to wrap my head around it. I tried to find a fix myself, but I am fairly new here and I have been unsuccessful at solving it myself. I would greatly appreciate any help.

Thank you so much.

**Comment by bertho-zero** [comment]
Is it possible to share the error log here? It could give me a clue.

**Comment by jackdarl** [comment]
Hey, nevermind!

I just ran the same code on a higher specced instance (**t2.medium**) and it ran flawlessly.

Guess the specifications of the free tier **t2.micro** instance are not sufficient.

Anyway, thank you so much @bertho-zero for the amazing repository. I can never thank you enough. :)

**Comment by jackdarl** [comment]
@bertho-zero : can you explain this error which happens during npm install:
```

npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global node-gyp@3.6.0 should be installed with -g

> phantomjs-prebuilt@2.1.14 install /home/ubuntu/test/unirail-site/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/ubuntu/test/unirail-site/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1493446426081/phantomjs-2.1.1-linux-x86_64 -> /home/ubuntu/test/unirail-site/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/ubuntu/test/unirail-site/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> node-sass@4.5.2 install /home/ubuntu/test/unirail-site/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/ubuntu/.npm/node-sass/4.5.2/linux-x64-48_binding.node

> node-sass@4.5.2 postinstall /home/ubuntu/test/unirail-site/node_modules/node-sass
> node scripts/build.js

Binary found at /home/ubuntu/test/unirail-site/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Binary is fine

> react-redux-universal-hot-example@0.9.0 postinstall /home/ubuntu/test/unirail-site
> concurrently "npm run build" "npm run build-dlls"

[0] 
[0] > react-redux-universal-hot-example@0.9.0 build /home/ubuntu/test/unirail-site
[0] > better-npm-run build
[0] 
[1] 
[1] > react-redux-universal-hot-example@0.9.0 build-dlls /home/ubuntu/test/unirail-site
[1] > webpack --colors --display-error-details --config webpack/vendor.config.js
[1] 
[0] running better-npm-run in /home/ubuntu/test/unirail-site
[0] Executing script: build
[0] 
[0] to be executed: webpack --colors --display-error-details --config=webpack/prod.config.js 
[0] clean-webpack-plugin: /home/ubuntu/test/unirail-site/static/dist has been removed.
[0] clean-webpack-plugin: /home/ubuntu/test/unirail-site/static/service-worker.js has been removed.
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/448c34a56d699c29117adc64c43affeb.woff2" (18 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/674f50d287a8c48dc19ba404d20fe713.eot" (166 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/89889688147bd7575d6327160d64e760.svg" (109 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/912ec66d7572ff821749319396470bde.svg" (444 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/af7ae505a9eed503f8b8e6982036873e.woff2" (77.2 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/b06871f281fee6b241d60582ae9369b9.ttf" (166 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/e18bbf611f2a2e43afc071aa2f4e1512.ttf" (45.4 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/f4769f9bdb7466be65088239c12046d1.eot" (20.1 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/fa2772327f55d8198301fdb8bcfc8158.woff" (23.4 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/fee66e712a8a08eef5805a46892932ad.woff" (98 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/index.html" (3.19 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/main-54d5f1baa60b238cab88.css" (34.8 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/dist/main-54d5f1baa60b238cab88.js" (223 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/favicon.png" (2.71 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/launcher-icon-2x.png" (8.1 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/launcher-icon-3x.png" (14.2 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/launcher-icon-4x.png" (22.5 kB)
[0] Caching static resource "/home/ubuntu/test/unirail-site/static/logo.jpg" (22.8 kB)
[0] Total precache size is about 1.5 MB for 18 resources.
[0] Hash: 5151b4879445c4c12138
[0] Version: webpack 2.4.1
[0] Time: 6655ms
[0]                                  Asset       Size  Chunks                    Chunk Names
[0]  fa2772327f55d8198301fdb8bcfc8158.woff    23.4 kB          [emitted]         
[0]                             index.html    3.19 kB          [emitted]         
[0] af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]         
[0]  fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]         
[0]   b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]         
[0]   912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  [big]  
[0]   f4769f9bdb7466be65088239c12046d1.eot    20.1 kB          [emitted]         
[0]   674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]         
[0] 448c34a56d699c29117adc64c43affeb.woff2      18 kB          [emitted]         
[0]   e18bbf611f2a2e43afc071aa2f4e1512.ttf    45.4 kB          [emitted]         
[0]   89889688147bd7575d6327160d64e760.svg     109 kB          [emitted]         
[0]           main-54d5f1baa60b238cab88.js     223 kB       0  [emitted]         main
[0]          main-54d5f1baa60b238cab88.css    34.8 kB       0  [emitted]         main
[0]      main-54d5f1baa60b238cab88.css.map  106 bytes       0  [emitted]         main
[0]    [1] ./~/bootstrap-loader/loader.js 123 bytes {0} [built]
[0]    [2] ./~/font-awesome-webpack/index.loader.js!./src/theme/font-awesome.config.prod.js 324 bytes {0} [built]
[0]    [3] ./src/client.js 1.27 kB {0} [built] [failed] [1 error]
[0]    [5] ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js 2.29 kB {0} [built]
[0]    [6] ./~/bootstrap-loader/lib/bootstrap.scripts.loader.js?{"bootstrapVersion":3,"useCustomIconFontPath":false,"extractStyles":false,"styleLoaders":["style","css","sass"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/home/ubuntu/test/unirail-site/~/bootstrap-loader/.bootstraprc-3-default","bootstrapPath":"/home/ubuntu/test/unirail-site/~/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./~/bootstrap-loader/no-op.js 813 bytes {0} [built]
[0]    [8] ./~/bootstrap-sass/assets/javascripts/bootstrap/alert.js 2.28 kB {0} [built]
[0]    [9] ./~/bootstrap-sass/assets/javascripts/bootstrap/button.js 3.82 kB {0} [built]
[0]   [10] ./~/bootstrap-sass/assets/javascripts/bootstrap/carousel.js 7.14 kB {0} [built]
[0]   [11] ./~/bootstrap-sass/assets/javascripts/bootstrap/collapse.js 5.99 kB {0} [built]
[0]   [12] ./~/bootstrap-sass/assets/javascripts/bootstrap/dropdown.js 4.74 kB {0} [built]
[0]   [13] ./~/bootstrap-sass/assets/javascripts/bootstrap/modal.js 9.99 kB {0} [built]
[0]   [14] ./~/bootstrap-sass/assets/javascripts/bootstrap/popover.js 3.16 kB {0} [built]
[0]   [23] ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/style-loader!./~/css-loader!./~/less-loader/dist!./~/font-awesome-webpack/font-awesome-styles.loader.js!./src/theme/font-awesome.config.prod.js 41 bytes {0} [built]
[0]   [27] ./~/style-loader!./~/css-loader!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"useCustomIconFontPath":false,"extractStyles":false,"styleLoaders":["style","css","sass"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/home/ubuntu/test/unirail-site/~/bootstrap-loader/.bootstraprc-3-default","bootstrapPath":"/home/ubuntu/test/unirail-site/~/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./~/bootstrap-loader/no-op.js 4.25 kB {0} [built]
[0]   [33] multi bootstrap-loader font-awesome-webpack!./src/theme/font-awesome.config.prod.js ./src/client.js 52 bytes {0} [built]
[0]     + 19 hidden modules
[0] 
[0] ERROR in ./src/client.js
[0] Module build failed: SyntaxError: Unexpected token (52:29)
[0] 
[0]   50 |     // if (online) app.authenticate().catch(() => null);
[0]   51 | 
[0] > 52 |     const data = !online ? { ...storedData, ...window.__data, online } : { ...window.__data, online };
[0]      |                              ^
[0]   53 |     const store = createStore(browserHistory, { client, app, restApp }, data, offlinePersistConfig);
[0]   54 |     const history = syncHistoryWithStore(browserHistory, store);
[0]   55 | 
[0] 
[0] BabelLoaderError: SyntaxError: Unexpected token (52:29)
[0] 
[0]   50 |     // if (online) app.authenticate().catch(() => null);
[0]   51 | 
[0] > 52 |     const data = !online ? { ...storedData, ...window.__data, online } : { ...window.__data, online };
[0]      |                              ^
[0]   53 |     const store = createStore(browserHistory, { client, app, restApp }, data, offlinePersistConfig);
[0]   54 |     const history = syncHistoryWithStore(browserHistory, store);
[0]   55 | 
[0] 
[0]     at transpile (/home/ubuntu/test/unirail-site/node_modules/babel-loader/lib/index.js:61:13)
[0]     at Object.module.exports (/home/ubuntu/test/unirail-site/node_modules/babel-loader/lib/index.js:163:20)
[0]  @ multi bootstrap-loader font-awesome-webpack!./src/theme/font-awesome.config.prod.js ./src/client.js
[0] 
[0] ERROR in   Error: Child compilation failed:
[0]   Module build failed: SyntaxError: Unexpected token (6:57)
[0]     4 | 
[0]     5 | export default function () {
[0]   > 6 |   return `<!doctype html>${R  eactDOM.renderToStaticMarkup(<Html />)}`;
[0]       |                                                            ^
[0]     7 | }
[0]     8 | 
[0]   :
[0]   BabelLoaderError: SyntaxError: Unexpected token (6:57)
[0]     4 | 
[0]     5 | export default function () {
[0]   > 6 |   return `<!doctype html>${R  eactDOM.renderToStaticMarkup(<Html />)}`;
[0]       |                                                            ^
[0]     7 | }
[0]     8 | 
[0]   
[0]   - compiler.js:76 
[0]     [unirail-site]/[html-webpack-plugin]/lib/compiler.js:76:16
[0]   
[0]   - Compiler.js:291 Compiler.<anonymous>
[0]     [unirail-site]/[webpack]/lib/Compiler.js:291:10
[0]   
[0]   - Compiler.js:494 
[0]     [unirail-site]/[webpack]/lib/Compiler.js:494:13
[0]   
[0]   - Tapable.js:138 next
[0]     [unirail-site]/[tapable]/lib/Tapable.js:138:11
[0]   
[0]   - CachePlugin.js:62 Compiler.<anonymous>
[0]     [unirail-site]/[webpack]/lib/CachePlugin.js:62:5
[0]   
[0]   - Tapable.js:142 Compiler.applyPluginsAsyncSeries
[0]     [unirail-site]/[tapable]/lib/Tapable.js:142:13
[0]   
[0]   - Compiler.js:491 
[0]     [unirail-site]/[webpack]/lib/Compiler.js:491:10
[0]   
[0]   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
[0]     [unirail-site]/[tapable]/lib/Tapable.js:131:46
[0]   
[0]   - Compilation.js:645 self.applyPluginsAsync.err
[0]     [unirail-site]/[webpack]/lib/Compilation.js:645:19
[0]   
[0]   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
[0]     [unirail-site]/[tapable]/lib/Tapable.js:131:46
[0]   
[0]   - Compilation.js:636 self.applyPluginsAsync.err
[0]     [unirail-site]/[webpack]/lib/Compilation.js:636:11
[0]   
[0]   - Tapable.js:138 next
[0]     [unirail-site]/[tapable]/lib/Tapable.js:138:11
[0]   
[0]   - UglifyJsPlugin.js:230 Compilation.compilation.plugin
[0]     [unirail-site]/[webpack]/lib/optimize/UglifyJsPlugin.js:230:5
[0]   
[0]   - Tapable.js:142 Compilation.applyPluginsAsyncSeries
[0]     [unirail-site]/[tapable]/lib/Tapable.js:142:13
[0]   
[0]   - Compilation.js:631 self.applyPluginsAsync.err
[0]     [unirail-site]/[webpack]/lib/Compilation.js:631:10
[0]   
[0]   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
[0]     [unirail-site]/[tapable]/lib/Tapable.js:131:46
[0]   
[0]   - Compilation.js:627 sealPart2
[0]     [unirail-site]/[webpack]/lib/Compilation.js:627:9
[0]   
[0]   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
[0]     [unirail-site]/[tapable]/lib/Tapable.js:131:46
[0]   
[0]   - Compilation.js:575 Compilation.seal
[0]     [unirail-site]/[webpack]/lib/Compilation.js:575:8
[0]   
[0]   - Compiler.js:488 
[0]     [unirail-site]/[webpack]/lib/Compiler.js:488:16
[0]   
[0]   - Tapable.js:225 
[0]     [unirail-site]/[tapable]/lib/Tapable.js:225:11
[0]   
[0]   - Compilation.js:477 _addModuleChain
[0]     [unirail-site]/[webpack]/lib/Compilation.js:477:11
[0]   
[0]   - Compilation.js:448 processModuleDependencies.err
[0]     [unirail-site]/[webpack]/lib/Compilation.js:448:13
[0]   
[0]   - next_tick.js:73 _combinedTickCallback
[0]     internal/process/next_tick.js:73:7
[0]   
[0]   - next_tick.js:104 process._tickCallback
[0]     internal/process/next_tick.js:104:9
[0]   
[0] 
[0] Child html-webpack-plugin for "index.html":
[0]        [0] ./~/html-webpack-plugin/lib/loader.js!./src/pwa.js 621 bytes {0} [built] [failed] [1 error]
[0]     
[0]     ERROR in ./~/html-webpack-plugin/lib/loader.js!./src/pwa.js
[0]     Module build failed: SyntaxError: Unexpected token (6:57)
[0]     
[0]       4 | 
[0]       5 | export default function () {
[0]     > 6 |   return `<!doctype html>${ReactDOM.renderToStaticMarkup(<Html />)}`;
[0]         |                                                          ^
[0]       7 | }
[0]       8 | 
[0]     
[0]     BabelLoaderError: SyntaxError: Unexpected token (6:57)
[0]     
[0]       4 | 
[0]       5 | export default function () {
[0]     > 6 |   return `<!doctype html>${ReactDOM.renderToStaticMarkup(<Html />)}`;
[0]         |                                                          ^
[0]       7 | }
[0]       8 | 
[0]     
[0]         at transpile (/home/ubuntu/test/unirail-site/node_modules/babel-loader/lib/index.js:61:13)
[0]         at Object.module.exports (/home/ubuntu/test/unirail-site/node_modules/babel-loader/lib/index.js:163:20)
[0] Child extract-text-webpack-plugin:
[0]                                      Asset     Size  Chunks                    Chunk Names
[0]       674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]         
[0]     af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]         
[0]      fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]         
[0]       b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]         
[0]       912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]  
[0]        [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
[0]        [1] ./~/font-awesome/fonts/fontawesome-webfont.eot 82 bytes {0} [built]
[0]        [2] ./~/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0 82 bytes {0} [built]
[0]        [3] ./~/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 84 bytes {0} [built]
[0]        [4] ./~/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0 83 bytes {0} [built]
[0]        [5] ./~/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0 82 bytes {0} [built]
[0]        [6] ./~/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0 82 bytes {0} [built]
[0]        [7] ./~/base64-js/index.js 3.48 kB {0} [built]
[0]        [8] ./~/buffer/index.js 48.6 kB {0} [built]
[0]        [9] ./~/buffer/~/isarray/index.js 132 bytes {0} [built]
[0]       [10] ./~/css-loader!./~/less-loader/dist!./~/font-awesome-webpack/font-awesome-styles.loader.js!./src/theme/font-awesome.config.prod.js 39.3 kB {0} [built]
[0]       [11] ./~/ieee754/index.js 2.05 kB {0} [built]
[0]       [12] (webpack)/buildin/global.js 509 bytes {0} [built]
[0] 
[0] npm
[0]  
[0] ERR!
[0]  Linux 4.4.0-1013-aws
[0] npm
[0]  
[0] ERR!
[0]  
[0] argv
[0]  "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
[0] npm
[0]  
[0] ERR!
[0]  
[0] node
[0]  v6.10.2
[0] npm
[0]  
[0] ERR!
[0]  
[0] npm 
[0]  v3.10.10
[0] npm
[0]  
[0] ERR!
[0]  
[0] code
[0]  ELIFECYCLE
[0] npm
[0]  ERR! react-redux-universal-hot-example@0.9.0 build: `better-npm-run build`
[0] npm ERR! Exit status 2
[0] npm ERR! 
[0] npm ERR! Failed at the react-redux-universal-hot-example@0.9.0 build script 'better-npm-run build'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the react-redux-universal-hot-example package,
[0] npm ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     better-npm-run build
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs react-redux-universal-hot-example
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls react-redux-universal-hot-example
[0] npm ERR! There is likely additional logging output above.
[0] 
[0] npm
[0]  
[0] ERR!
[0]  Please include the following file with any support request:
[0] npm
[0]  
[0] ERR!
[0]      /home/ubuntu/test/unirail-site/npm-debug.log
[0] npm run build exited with code 1
[1] Hash: f787c3daa6acead58186
[1] Version: webpack 2.4.1
[1] Time: 10809ms
[1]          Asset     Size  Chunks                    Chunk Names
[1] dll__vendor.js  7.07 MB       0  [emitted]  [big]  vendor
[1]    [0] ./~/react/react.js 56 bytes {0} [built]
[1]    [4] ./~/babel-runtime/helpers/extends.js 544 bytes {0} [built]
[1]    [5] ./~/babel-runtime/helpers/inherits.js 1.11 kB {0} [built]
[1]    [6] ./~/babel-runtime/helpers/possibleConstructorReturn.js 542 bytes {0} [built]
[1]    [7] ./~/babel-runtime/helpers/objectWithoutProperties.js 280 bytes {0} [built]
[1]   [32] ./~/react-dom/index.js 59 bytes {0} [built]
[1]   [71] ./~/react-redux/es/index.js 194 bytes {0} [built]
[1]  [124] ./~/babel-runtime/helpers/typeof.js 1.07 kB {0} [built]
[1]  [125] ./~/redux/es/index.js 1.08 kB {0} [built]
[1]  [196] ./~/babel-runtime/core-js/array/from.js 91 bytes {0} [built]
[1]  [197] ./~/babel-runtime/core-js/object/assign.js 94 bytes {0} [built]
[1]  [198] ./~/babel-runtime/core-js/object/define-property.js 103 bytes {0} [built]
[1]  [508] ./~/multireducer/lib/index.js 929 bytes {0} [built]
[1]  [520] ./~/superagent/lib/client.js 22 kB {0} [built]
[1] [1223] dll vendor 12 bytes {0} [built]
[1]     + 1210 hidden modules
[1] npm run build-dlls exited with code 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN multireducer@3.1.0 requires a peer of immutable@^3.0.0 but none was installed.
npm WARN bootstrap-loader@2.0.0 requires a peer of extract-text-webpack-plugin@>=2.1.0 but none was installed.
npm ERR! Linux 4.4.0-1013-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-redux-universal-hot-example@0.9.0 postinstall: `concurrently "npm run build" "npm run build-dlls"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-universal-hot-example@0.9.0 postinstall script 'concurrently "npm run build" "npm run build-dlls"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-universal-hot-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run build" "npm run build-dlls"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-universal-hot-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-universal-hot-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/test/unirail-site/npm-debug.log
ubuntu@ip-172-31-30-50:~/
```

Even though I have found a way around the problem, this error bugs me. It just doesn't make sense that the same code can build once but fail another time. I believe it's a mistake from my end, but I am not being able to figure it out. For the record, I have reproduced this from the same higher specced instance that (seemingly) fixed my issue, and that's all the more reason why this error puzzles me.

**Comment by MHerszak** [comment]
This is a total shot in the dark but do you have .babelrc available?

**Comment by jackdarl** [comment]
Sorry for the late reply. 
@MHerszak : Yes I do. :(

**Comment by MHerszak** [comment]
@jackdarl and all packages are properly installed? It seems like there is no babel transpiler.
