### ISSUE TITLE
Logout failed

### ISSUE THREAD

**Issue by phamvuau** [bertho-zero/react-redux-universal-hot-example#349]
When I clicked logout link on the top bar, nothing happened, the node server printed
`
/Users/Au/web/node_modules/feathers-authentication/lib/socket/handler.js:75
         socket._feathers.body = {};
 TypeError: Cannot set property 'body' of undefined
    at Socket.logout (/Users/Au/web/node_modules/feathers-authentication/lib/socket/handler.js:75:31)
     at emitOne (events.js:115:13)
     at Socket.emit (events.js:210:7)
     at /Users/Au/web/node_modules/socket.io/lib/socket.js:513:12
     at _combinedTickCallback (internal/process/next_tick.js:131:7)
     at process._tickCallback (internal/process/next_tick.js:180:9)
 proxy error { Error: connect ECONNREFUSED 127.0.0.1:3030
     at Object._errnoException (util.js:1021:11)
     at _exceptionWithHostPort (util.js:1043:20)
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
   code: 'ECONNREFUSED',

`
Anybody knows how to fix it?

**Comment by bertho-zero** [comment]
Thanks, I have open this pull request: https://github.com/feathersjs/authentication/pull/604
