### ISSUE TITLE
utils/getChunks.js:32 throw new Error('Unable to load chunks'); while running app in development

### ISSUE THREAD

**Issue by Swapnilchavan18** [bertho-zero/react-redux-universal-hot-example#361]

**Comment by bertho-zero** [comment]
I need more details to help you.

What are you doing to have this error? just `yarn dev` or` npm run dev`?
Does it work for a moment before having this error or not at all?
Do you have this mistake by doing some particular things?

Do you have this error after the 60s of timeout or not? have you tried to increase the timeout of the waitChunks function?

https://github.com/bertho-zero/react-redux-universal-hot-example/blob/38c1a225125640a35f91f3003114710986cd70c2/src/server.js#L163

like this:
```js
await waitChunks(chunksPath, 120000); // for 2 minutes
```

**Comment by Swapnilchavan18** [comment]
I run with npm run dev, it works but after I change code it starts rebuilding and gives error,let me check by increasing timeout

**Comment by bertho-zero** [comment]
Can you tell me which operating system you use?
And can you log the error in the onChange here:
https://github.com/bertho-zero/react-redux-universal-hot-example/blob/38c1a225125640a35f91f3003114710986cd70c2/src/utils/getChunks.js#L74-L89

like this:
```js
console.log('waitChunks onChange error:', err); // <--- add this line
throw new Error('Unable to load chunks');
```

---

And can you try to replace this code:
https://github.com/bertho-zero/react-redux-universal-hot-example/blob/38c1a225125640a35f91f3003114710986cd70c2/src/utils/getChunks.js#L35-L44
by the following:
```js
 const watcher = fs.watch(path, 'utf8', eventType => { 
   console.log('waitChunks eventType:', eventType); // <--- add this line
   if (eventType !== 'change') { 
     return onChange(new Error(`waitFile: file was renamed: ${path}`)); 
   } 
   fs.readFile(path, 'utf8', (err2, data) => {
     console.log('New chunks data:', data); // <--- add this line
     if (err2) return onChange(err2); 
     loaded = true; 
     onChange(null, data); 
   }); 
 }); 
```

**Comment by Swapnilchavan18** [comment]
It still gives same error sometimes(not always), that happen when rebuilding takes time or there is some error with code

**Comment by bertho-zero** [comment]
Can you give me the error logs that should appear after the console.log that I asked you to display?

**Comment by bblurock** [comment]
I encountered the same issue so I can provide with my error log aforementioned.
```
waitChunks eventType: change
waitChunks eventType: rename
waitChunks onChange error: Error: waitFile: file was renamed: /Users/bblurock/Documents/Development/ownrides/ownrides-fnd/static/dist/loadable-chunks.json
     at FSWatcher.<anonymous> (/Users/bblurock/Documents/Development/ownrides/ownrides-fnd/src/utils/getChunks.js:38:29)
     at emitTwo (events.js:106:13)
     at FSWatcher.emit (events.js:191:7)
     at FSEvent.FSWatcher._handle.onchange (fs.js:1412:12)
```

where the output of `console.log('New chunks data:', data);` is extremely long, consist all the chunks being used, here are some partial results:
```
[1] "./Survey": [
[1]     {
[1]       "id": 275,
[1]       "name": "./src/containers/Survey/Survey.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "!!../../../node_modules/css-loader/index.js?{\"modules\":true,\"importLoaders\":2,\"sourceMap\":true,\"localIdentName\":\"[local]___[hash:base64:5]\"}!../../../node_modules/postcss-loader/lib/index.js?{\"sourceMap\":true}!../../../node_modules/sass-loader/lib/loader.js?{\"outputStyle\":\"expanded\",\"sourceMap\":true}!./Survey.scss": [
[1]     {
[1]       "id": 940,
[1]       "name": "./node_modules/css-loader/index.js?{\"modules\":true,\"importLoaders\":2,\"sourceMap\":true,\"localIdentName\":\"[local]___[hash:base64:5]\"}!./node_modules/postcss-loader/lib/index.js?{\"sourceMap\":true}!./node_modules/sass-loader/lib/loader.js?{\"outputStyle\":\"expanded\",\"sourceMap\":true}!./src/containers/Survey/Survey.scss",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "./RadioButton": [
[1]     {
[1]       "id": 942,
[1]       "name": "./node_modules/material-ui/RadioButton/RadioButton.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "redux/modules/survey": [
[1]     {
[1]       "id": 963,
[1]       "name": "./src/redux/modules/survey.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "material-ui/RadioButton": [
[1]     {
[1]       "id": 964,
[1]       "name": "./node_modules/material-ui/RadioButton/index.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "../internal/EnhancedSwitch": [
[1]     {
[1]       "id": 965,
[1]       "name": "./node_modules/material-ui/internal/EnhancedSwitch.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "../svg-icons/toggle/radio-button-unchecked": [
[1]     {
[1]       "id": 966,
[1]       "name": "./node_modules/material-ui/svg-icons/toggle/radio-button-unchecked.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "../svg-icons/toggle/radio-button-checked": [
[1]     {
[1]       "id": 967,
[1]       "name": "./node_modules/material-ui/svg-icons/toggle/radio-button-checked.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "./RadioButtonGroup": [
[1]     {
[1]       "id": 968,
[1]       "name": "./node_modules/material-ui/RadioButton/RadioButtonGroup.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "material-ui/TextField": [
[1]     {
[1]       "id": 969,
[1]       "name": "./node_modules/material-ui/TextField/index.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "./TextField": [
[1]     {
[1]       "id": 970,
[1]       "name": "./node_modules/material-ui/TextField/TextField.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "./EnhancedTextarea": [
[1]     {
[1]       "id": 971,
[1]       "name": "./node_modules/material-ui/TextField/EnhancedTextarea.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "./TextFieldHint": [
[1]     {
[1]       "id": 972,
[1]       "name": "./node_modules/material-ui/TextField/TextFieldHint.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "./TextFieldLabel": [
[1]     {
[1]       "id": 973,
[1]       "name": "./node_modules/material-ui/TextField/TextFieldLabel.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "./TextFieldUnderline": [
[1]     {
[1]       "id": 974,
[1]       "name": "./node_modules/material-ui/TextField/TextFieldUnderline.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "lodash.throttle": [
[1]     {
[1]       "id": 975,
[1]       "name": "./node_modules/lodash.throttle/index.js",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "./Survey.scss": [
[1]     {
[1]       "id": 976,
[1]       "name": "./src/containers/Survey/Survey.scss",
[1]       "file": "0-219407e342b8987aa02a.js"
[1]     }
[1]   ],
[1]   "./Register": [
[1]     {
[1]       "id": 274,
[1]       "name": "./src/containers/Register/Register.js",
[1]       "file": "1-a5402e06b94e0a06ebeb.js"
[1]     }
[1]   ],
[1]   "utils/validation": [
[1]     {
[1]       "id": 938,
[1]       "name": "./src/utils/validation.js",
[1]       "file": "1-a5402e06b94e0a06ebeb.js"
[1]     },
[1]     {
[1]       "id": 938,
[1]       "name": "./src/utils/validation.js",
[1]       "file": "2-40cf4c699469ff519a66.js"
[1]     }
[1]   ],
[1]   "undefined": [
[1]     {
[1]       "id": 939,
[1]       "name": "./node_modules/babel-runtime/core-js/number/is-integer.js",
[1]       "file": "1-a5402e06b94e0a06ebeb.js"
[1]     },
[1]     {
[1]       "id": 939,
[1]       "name": "./node_modules/babel-runtime/core-js/number/is-integer.js",
[1]       "file": "2-40cf4c699469ff519a66.js"
[1]     },
[1]     {
[1]       "id": 952,
[1]       "name": "./node_modules/core-js/library/modules/_global.js",
[1]       "file": "3-4e7d1a1d227259e1bf3d.js"
[1]     },
[1]     {
[1]       "id": 953,
[1]       "name": "./node_modules/core-js/library/modules/_export.js",
[1]       "file": "3-4e7d1a1d227259e1bf3d.js"
[1]     },
[1]     {
[1]       "id": 954,
[1]       "name": "./node_modules/core-js/library/modules/_core.js",
[1]       "file": "3-4e7d1a1d227259e1bf3d.js"
[1]     },
[1]     {
[1]       "id": 0,
[1]       "name": "dll-reference DLL_vendor_4f63eff6f8b975f3fa83",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 1,
[1]       "name": "./node_modules/react/index.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 3,
[1]       "name": "./node_modules/prop-types/index.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 4,
[1]       "name": "./node_modules/babel-runtime/helpers/extends.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 5,
[1]       "name": "./node_modules/babel-runtime/helpers/classCallCheck.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 6,
[1]       "name": "./node_modules/babel-runtime/helpers/possibleConstructorReturn.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 7,
[1]       "name": "./node_modules/babel-runtime/helpers/inherits.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 8,
[1]       "name": "./node_modules/babel-runtime/core-js/object/get-prototype-of.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 9,
[1]       "name": "./node_modules/babel-runtime/helpers/createClass.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 10,
[1]       "name": "./node_modules/babel-runtime/helpers/objectWithoutProperties.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 13,
[1]       "name": "./node_modules/webpack/buildin/global.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 14,
[1]       "name": "./node_modules/react-dom/index.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 15,
[1]       "name": "./node_modules/react-redux/es/index.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 18,
[1]       "name": "./node_modules/babel-runtime/core-js/object/keys.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 21,
[1]       "name": "./node_modules/warning/browser.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 23,
[1]       "name": "./node_modules/webpack/buildin/module.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 32,
[1]       "name": "./node_modules/babel-runtime/regenerator/index.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 33,
[1]       "name": "./node_modules/babel-runtime/helpers/asyncToGenerator.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 39,
[1]       "name": "./node_modules/babel-runtime/helpers/toConsumableArray.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 40,
[1]       "name": "./node_modules/react-router-redux/es/index.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 42,
[1]       "name": "./node_modules/node-libs-browser/node_modules/process/browser.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 43,
[1]       "name": "./node_modules/object-assign/index.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 52,
[1]       "name": "./node_modules/react-router/es/index.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 53,
[1]       "name": "./node_modules/invariant/browser.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 74,
[1]       "name": "./node_modules/babel-runtime/core-js/promise.js",
[1]       "file": "main-3817d871304f94b67fd7.js"
[1]     },
[1]     {
[1]       "id": 84,
[1]       "name": "./no
```

**Comment by Swapnilchavan18** [comment]
Error log as below.
Error: waitFile: file was renamed: /Applications/XAMPP/xamppfiles/htdocs/test16/static/dist/loadable-chunks.json
[1]     at FSWatcher.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/test16/src/utils/getChunks.js:37:31)
[1]     at emitTwo (events.js:126:13)
[1]     at FSWatcher.emit (events.js:214:7)
[1]     at FSEvent.FSWatcher._handle.onchange (fs.js:1356:12)
[1] /Applications/XAMPP/xamppfiles/htdocs/test16/src/utils/getChunks.js:33
[1]                   throw new Error('Unable to load chunks');
