### ISSUE TITLE
react-icons module fail

### ISSUE THREAD

**Issue by joacub** [bertho-zero/react-redux-universal-hot-example#383]
fail this module when load, the babel not compiled right

`node_modules/react-icons/md/index.js:1
[1] (function (exports, require, module, __filename, __dirname) { export Md3dRotation from './3d-rotation';
[1]                                                               ^^^^^^
[1] 
[1] SyntaxError: Unexpected token export
[1]     at new Script (vm.js:51:7)
[1]     at createScript (vm.js:138:10)
[1]     at Object.runInThisContext (vm.js:199:10)
[1]     at Module._compile (module.js:624:28)
[1]     at Module._extensions..js (module.js:671:10)`

**Comment by bertho-zero** [comment]
You should import the builded version: `react-icons/md` -> `react-icons/lib/md`
