### ISSUE TITLE
webpackUniversalModuleDefinition not working with babel-runtime

### ISSUE THREAD

**Issue by p-rk** [bertho-zero/react-redux-universal-hot-example#401]
I created a javascript library using webpack i bundled it as library umd. I tried linking it this project using npm link but unfortunately I'm stuck with babel-runtime issue.

Error

```
 ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/Rama/Projects/npm-packages/js-utility-functions/lib"
	at /Users/Rama/Projects/hometown/hometown-mobile/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
	at Array.map (<anonymous>)
	at Function.normalisePlugins (/Users/Rama/Projects/hometown/hometown-mobile/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
	at OptionManager.mergeOptions (/Users/Rama/Projects/hometown/hometown-mobile/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
	at OptionManager.init (/Users/Rama/Projects/hometown/hometown-mobile/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
	at compile (/Users/Rama/Projects/hometown/hometown-mobile/node_modules/babel-register/lib/node.js:103:45)
	at loader (/Users/Rama/Projects/hometown/hometown-mobile/node_modules/babel-register/lib/node.js:144:14)
	at Object.require.extensions.(anonymous function) [as .js] (/Users/Rama/Projects/hometown/hometown-mobile/node_modules/babel-register/lib/node.js:154:7)
	at Module.load (module.js:573:32)
	at tryModuleLoad (module.js:513:12)
```

My library is working flawlessly in react create app

**Comment by bertho-zero** [comment]
You need to add `babel-runtime` and `babel-plugin-transform-runtime` in your module.
