### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by Ory4n** [bertho-zero/react-redux-universal-hot-example#435]
Hi I get a lot of issues after i do npm install. Can you please assist thanks.

Example errors:

error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

69 problems (69 errors, 0 warnings)
[0]   69 errors, 0 warnings potentially fixable with the `--fix` option.

 @ ./src/components/WidgetForm/widgetValidation.js 8:18-45
[0]  @ ./src/components/WidgetForm/WidgetForm.js
[0]  @ ./src/containers/Widgets/Widgets.js
[0]  @ ./src/containers/Widgets/Loadable.js
[0]  @ ./src/routes.js
[0]  @ ./src/client.js
[0]  @ multi webpack-hot-middleware/client?path=http://localhost:3001/__webpack_hmr react-hot-loader/patch bootstrap-loader ./src/client.js
[0] webpack built 174ac3306ef8f2452d3b in 40338ms
[0] i ｢wdm｣: Compiled with warnings.
[2] { NotFound: Page not found
[2]     at new NotFound (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\@feathersjs\errors\lib\index.js:114:17)
[2]     at C:/Users/infoo/Documents/GitHub/react-redux-universal-hot-example/api/middleware/notFound.js:5:10
[2]     at Layer.handle [as handle_request] (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\express\lib\router\layer.js:95:5)
[2]     at trim_prefix (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\express\lib\router\index.js:317:13)
[2]     at C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\express\lib\router\index.js:284:7
[2]     at Function.process_params (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\express\lib\router\index.js:335:12)
[2]     at next (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\express\lib\router\index.js:275:10)
[2]     at _callee$ (C:/Users/infoo/Documents/GitHub/react-redux-universal-hot-example/api/middleware/actionHandler.js:33:7)
[2]     at tryCatch (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\regenerator-runtime\runtime.js:62:40)
[2]     at Generator.invoke [as _invoke] (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\regenerator-runtime\runtime.js:296:22)
[2]   type: 'FeathersError',
[2]   name: 'NotFound',
[2]   message: 'Page not found',
[2]   code: 404,
[2]   className: 'not-found',
[2]   data: undefined,
[2]   errors: {} }
[2] GET / 404 7.368 ms - 11252
[2] { NotFound: Page not found
[2]     at new NotFound (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\@feathersjs\errors\lib\index.js:114:17)
[2]     at C:/Users/infoo/Documents/GitHub/react-redux-universal-hot-example/api/middleware/notFound.js:5:10
[2]     at Layer.handle [as handle_request] (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\express\lib\router\layer.js:95:5)
[2]     at trim_prefix (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\express\lib\router\index.js:317:13)
[2]     at C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\express\lib\router\index.js:284:7
[2]     at Function.process_params (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\express\lib\router\index.js:335:12)
[2]     at next (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\express\lib\router\index.js:275:10)
[2]     at _callee$ (C:/Users/infoo/Documents/GitHub/react-redux-universal-hot-example/api/middleware/actionHandler.js:33:7)
[2]     at tryCatch (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\regenerator-runtime\runtime.js:62:40)
[2]     at Generator.invoke [as _invoke] (C:\Users\infoo\Documents\GitHub\react-redux-universal-hot-example\node_modules\regenerator-runtime\runtime.js:296:22)
[2]   type: 'FeathersError',
[2]   name: 'NotFound',
[2]   message: 'Page not found',
[2]   code: 404,
[2]   className: 'not-found',
[2]   data: undefined,
[2]   errors: {} }
[2] GET / 404 7.644 ms - 11252

**Comment by bertho-zero** [comment]
For your eslint error you need to add `"linebreak-style": ["error", "windows"]` or `"linebreak-style": "off"` in your `.eslintrc`.
