### ISSUE TITLE
socketAuth error in incognito happens on first start

### ISSUE THREAD

**Issue by arfianadam** [bertho-zero/react-redux-universal-hot-example#50]
I run `npm run dev` and open `localhost:3000` in chrome's incognito window. The page loads just fine until I check the terminal. It shows up an error:

```
/home/arfianadam/work/adam/react-redux-universal-hot-example/api/services/authentication/socketAuth.js:42
     var accessToken = cookies['feathers-jwt'] || null;
                              ^
 
 TypeError: Cannot read property 'feathers-jwt' of undefined
     at Array.<anonymous> (/home/arfianadam/work/adam/react-redux-universal-hot-example/api/services/authentication/socketAuth.js:15:25)
     at run (/home/arfianadam/work/adam/react-redux-universal-hot-example/node_modules/socket.io/lib/namespace.js:119:11)
     at /home/arfianadam/work/adam/react-redux-universal-hot-example/node_modules/socket.io/lib/namespace.js:127:7
     at Array.<anonymous> (/home/arfianadam/work/adam/react-redux-universal-hot-example/node_modules/feathers-socketio/lib/index.js:27:13)
     at run (/home/arfianadam/work/adam/react-redux-universal-hot-example/node_modules/socket.io/lib/namespace.js:119:11)
     at Namespace.run (/home/arfianadam/work/adam/react-redux-universal-hot-example/node_modules/socket.io/lib/namespace.js:131:3)
     at Namespace.add (/home/arfianadam/work/adam/react-redux-universal-hot-example/node_modules/socket.io/lib/namespace.js:160:8)
     at Client.connect (/home/arfianadam/work/adam/react-redux-universal-hot-example/node_modules/socket.io/lib/client.js:76:20)
     at Server.onconnection (/home/arfianadam/work/adam/react-redux-universal-hot-example/node_modules/socket.io/lib/index.js:367:10)
     at emitOne (events.js:96:13)
 proxy error { Error: connect ECONNREFUSED 127.0.0.1:3030
     at Object.exports._errnoException (util.js:1026:11)
     at exports._exceptionWithHostPort (util.js:1049:20)
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
   code: 'ECONNREFUSED',
   errno: 'ECONNREFUSED',
   syscall: 'connect',
   address: '127.0.0.1',
   port: 3030 }
 /home/arfianadam/work/adam/react-redux-universal-hot-example/src/server.js:123
     res.writeHead(500, { 'content-type': 'application/json' });
         ^
 
 TypeError: res.writeHead is not a function
     at ProxyServer.<anonymous> (/home/arfianadam/work/adam/react-redux-universal-hot-example/src/server.js:61:9)
     at ProxyServer.emit (/home/arfianadam/work/adam/react-redux-universal-hot-example/node_modules/eventemitter3/index.js:144:27)
     at ClientRequest.onOutgoingError (/home/arfianadam/work/adam/react-redux-universal-hot-example/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:151:16)
     at emitOne (events.js:96:13)
     at ClientRequest.emit (events.js:188:7)
     at Socket.socketErrorListener (_http_client.js:310:9)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at emitErrorNT (net.js:1276:8)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
```
The thing is, it only shows up on first run. After I rerun the `npm run dev`, the error won't show up anymore. Maybe it is related to serviceworker or js file cached after the first run?

**Comment by MHerszak** [comment]
I got the same error when I started in normal mode for the first time.

**Comment by bertho-zero** [comment]
It's fixed ;)

**Comment by arfianadam** [comment]
@bertho-zero ah thanks!

**Comment by ducnvhn** [comment]
I have no problem when I start with `npm run dev` but whenever I change the API server code, the API server restart and have this problem: 
```
res.writeHead(500, { 'content-type': 'application/json' });
[1]         ^
[1]
[1] TypeError: res.writeHead is not a function
[1]     at ProxyServer.<anonymous> (Path_to_prj/src/server.js:70:9)
[1]     at ProxyServer.emit (Path_to_prj\node_modules\eventemitter3\index.js:144:27)
[1]     at Socket.onOutgoingError (Path_to_prj\node_modules\http-proxy\lib\http-proxy\passes\ws-incoming.js:151:16)
[1]     at emitOne (events.js:101:20)
[1]     at Socket.emit (events.js:188:7)
[1]     at emitErrorNT (net.js:1271:8)
[1]     at _combinedTickCallback (internal/process/next_tick.js:74:11)
[1]     at process._tickCallback (internal/process/next_tick.js:98:9)
[2] ----
[2] ==> 🌎  API is running on port 3030
[2] ==> 💻  Send requests to http://localhost:3030
```
And then I have to stop and run `npm run dev` again to start API server as normal. 
Please help!
