### ISSUE TITLE
Piping error

### ISSUE THREAD

**Issue by goodguy000** [bertho-zero/react-redux-universal-hot-example#527]
Hi admin and everyone,
I am using Ubuntu, node v10.15, so when I install this project and run dev, I see the error in terminal and then my computer is freeze, cannot do anything after run dev.
So I tried to find out what reason, maybe it is piping issue. It's not support node v10, I try install node v8 and it's works fine. but with node v10 I got the tons of message:  **possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.**
Anyone can make something to fix it or change from pipping to another like nodemon or something.
Please look in to this.

**Comment by goodguy000** [comment]
@bertho-zero Please help me, look into this issue

**Comment by arman-mukatov** [comment]
@goodguy000, downgrade to @0.3.0 it solves the problem

**Comment by goodguy000** [comment]
Hi @arman-mukatov Thanks for your response. But I tried to change the version of piping to 0.3.0, when I save code then it is interrupted with error, and then I must run: yarn dev again.
Do you have any idea about replace piping by other else, I think piping is really old version, lastest version is 3 years ago. 
I am using nodejs 10.15
[2] internal/process/per_thread.js:198
[2]       throw errnoException(err, 'kill');
[2]       ^
[2]
[2] Error: kill ESRCH
[2]     at process.kill (internal/process/per_thread.js:198:13)
[2]     at FSWatcher.<anonymous> (C:\Working\projects\mec\node_modules\piping\lib\piping.js:87:19)
[2]     at FSWatcher.emit (events.js:189:13)
[2]     at FSWatcher.<anonymous> (C:\Working\projects\mec\node_modules\chokidar\index.js:196:15)
[2]     at FSWatcher._emit (C:\Working\projects\mec\node_modules\chokidar\index.js:238:5)
[2]     at FSWatcher.<anonymous> (C:\Working\projects\mec\node_modules\chokidar\lib\nodefs-handler.js:263:16)
[2]     at FSReqWrap.oncomplete (fs.js:154:5)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by goodguy000** [comment]
I tried to switch to window 10 to code, in Ubuntu It made ubuntu died after run dev.

**Comment by S1MB10T3** [comment]
Try running:
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p` 

It worked for me on Debain buster.

**Comment by goodguy000** [comment]
Thanks @S1MB10T3 I try with your commanh, it works.
