### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by sylc** [bertho-zero/react-redux-universal-hot-example#70]
Hi,

I've just clone the repo and performed `npm i` . I have the following error coming up:

[0] ERROR in ./src/client.js
[0] Module build failed: SyntaxError: C:/app/src/client.js: Unexpected token (50:2                      9)
[0]
[0]   48 |     // if (online) app.authenticate().catch(() => null);
[0]   49 |
[0] > 50 |     const data = !online ? { ...storedData, ...window.__data, online } : { ...window.__data, online };
[0]      |                              ^
[0]   51 |     const store = createStore(browserHistory, client, data, offlinePersistConfig);
[0]   52 |     const history = syncHistoryWithStore(browserHistory, store);
[0]   53 |
[0]
[0] BabelLoaderError: SyntaxError: C:/app/src/client.js: Unexpected token (50:29)
[0]
[0]   48 |     // if (online) app.authenticate().catch(() => null);
[0]   49 |
[0] > 50 |     const data = !online ? { ...storedData, ...window.__data, online } : { ...window.__data, online };
[0]      |                              ^
[0]   51 |     const store = createStore(browserHistory, client, data, offlinePersistConfig);
[0]   52 |     const history = syncHistoryWithStore(browserHistory, store);
[0]   53 |
[0]
[0]     at transpile (C:\app\node_modules\babel-loader\lib\index.js:52:13)
[0]     at Object.module.exports (C:\app\node_modules\babel-loader\lib\index.js:13                      3:12)
[0]  @ multi bootstrap-loader font-awesome-webpack!./src/theme/font-awesome.config.prod.js ./src/client.js
[0]
[0] ERROR in   Error: Child compilation failed:
[0]   Module build failed: SyntaxError: C:/Users/Sylvain/Documents/App/Perso/Outdoor  Cine/OutdoorCine2.6/src/pwa.js: Unexpected token (6:5                      7)
[0]     4 |
[0]     5 | export default function () {
[0]   > 6 |   return `<!doctype html>${R  eactDOM.renderToStaticMarkup(<Html />)}`;
[0]       |                                                            ^
[0]     7 | }
[0]     8 |
[0]   :
[0]   BabelLoaderError: SyntaxError: C:/Users/Sylvain/Documents/App/Perso/OutdoorCin  e/OutdoorCine2.6/src/pwa.js: Unexpected token (6:57)
[0]     4 |
[0]     5 | export default function () {
[0]   > 6 |   return `<!doctype html>${R  eactDOM.renderToStaticMarkup(<Html />)}`;
[0]       |                                                            ^
[0]     7 | }
[0]     8 |
[0]
[0]   - compiler.js:76
[0]     [OutdoorCine2.6]/[html-webpack-plugin]/lib/compiler.js:76:16
[0]
[0]   - Compiler.js:280 Compiler.<anonymous>
[0]     [OutdoorCine2.6]/[webpack]/lib/Compiler.js:280:10
[0]
[0]   - Compiler.js:480
[0]     [OutdoorCine2.6]/[webpack]/lib/Compiler.js:480:13
[0]
[0]   - Tapable.js:138 next
[0]     [OutdoorCine2.6]/[tapable]/lib/Tapable.js:138:11
[0]
[0]   - CachePlugin.js:62 Compiler.<anonymous>
[0]     [OutdoorCine2.6]/[webpack]/lib/CachePlugin.js:62:5
[0]
[0]   - Tapable.js:142 Compiler.applyPluginsAsyncSeries
[0]     [OutdoorCine2.6]/[tapable]/lib/Tapable.js:142:13
[0]
[0]   - Compiler.js:477
[0]     [OutdoorCine2.6]/[webpack]/lib/Compiler.js:477:10
[0]
[0]   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
[0]     [OutdoorCine2.6]/[tapable]/lib/Tapable.js:131:46
[0]
[0]   - Compilation.js:640 self.applyPluginsAsync.err
[0]     [OutdoorCine2.6]/[webpack]/lib/Compilation.js:640:19
[0]
[0]   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
[0]     [OutdoorCine2.6]/[tapable]/lib/Tapable.js:131:46
[0]
[0]   - Compilation.js:631 self.applyPluginsAsync.err
[0]     [OutdoorCine2.6]/[webpack]/lib/Compilation.js:631:11
[0]
[0]   - Tapable.js:138 next
[0]     [OutdoorCine2.6]/[tapable]/lib/Tapable.js:138:11
[0]
[0]   - UglifyJsPlugin.js:140 Compilation.compilation.plugin
[0]     [OutdoorCine2.6]/[webpack]/lib/optimize/UglifyJsPlugin.js:140:5
[0]
[0]   - Tapable.js:142 Compilation.applyPluginsAsyncSeries
[0]     [OutdoorCine2.6]/[tapable]/lib/Tapable.js:142:13
[0]
[0]   - Compilation.js:626 self.applyPluginsAsync.err
[0]     [OutdoorCine2.6]/[webpack]/lib/Compilation.js:626:10
[0]
[0]   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
[0]     [OutdoorCine2.6]/[tapable]/lib/Tapable.js:131:46
[0]
[0]   - Compilation.js:622 sealPart2
[0]     [OutdoorCine2.6]/[webpack]/lib/Compilation.js:622:9
[0]
[0]   - Tapable.js:131 Compilation.applyPluginsAsyncSeries
[0]     [OutdoorCine2.6]/[tapable]/lib/Tapable.js:131:46
[0]
[0]   - Compilation.js:570 Compilation.seal
[0]     [OutdoorCine2.6]/[webpack]/lib/Compilation.js:570:8
[0]
[0]   - Compiler.js:474
[0]     [OutdoorCine2.6]/[webpack]/lib/Compiler.js:474:16
[0]
[0]   - Tapable.js:225
[0]     [OutdoorCine2.6]/[tapable]/lib/Tapable.js:225:11
[0]
[0]   - Compilation.js:472 _addModuleChain
[0]     [OutdoorCine2.6]/[webpack]/lib/Compilation.js:472:11
[0]
[0]   - Compilation.js:443 processModuleDependencies.err
[0]     [OutdoorCine2.6]/[webpack]/lib/Compilation.js:443:13
[0]
[0]   - next_tick.js:67 _combinedTickCallback
[0]     internal/process/next_tick.js:67:7
[0]
[0]   - next_tick.js:98 process._tickCallback
[0]     internal/process/next_tick.js:98:9
[0]
[0]
[0] Child html-webpack-plugin for "index.html":
[0]        [0] ./~/html-webpack-plugin/lib/loader.js!./src/pwa.js 697 bytes {0} [built] [failed] [1 error]
[0]
[0]     ERROR in ./~/html-webpack-plugin/lib/loader.js!./src/pwa.js
[0]     Module build failed: SyntaxError: C:/app/src/pwa.js: Unexpected token (6:5                      7)
[0]
[0]       4 |
[0]       5 | export default function () {
[0]     > 6 |   return `<!doctype html>${ReactDOM.renderToStaticMarkup(<Html />)}`;
[0]         |                                                          ^
[0]       7 | }
[0]       8 |
[0]
[0]     BabelLoaderError: SyntaxError: C:/app/src/pwa.js: Unexpected token (6:57)
[0]
[0]       4 |
[0]       5 | export default function () {
[0]     > 6 |   return `<!doctype html>${ReactDOM.renderToStaticMarkup(<Html />)}`;
[0]         |                                                          ^
[0]       7 | }
[0]       8 |
[0]
[0]         at transpile (C:\app\node_modules\babel-loader\lib\index.js:52:13)
[0]         at Object.module.exports (C:\app\node_modules\babel-loader\lib\index.j                      s:133:12)
[0] Child extract-text-webpack-plugin:
[0]                                      Asset     Size  Chunks                    Chunk Names
[0]       674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]
[0]     af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]
[0]      fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]
[0]       b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]
[0]       912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]
[0]        [0] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[0]        [1] ./~/font-awesome/fonts/fontawesome-webfont.eot 82 bytes {0} [built]
[0]        [2] ./~/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0 82 bytes {0} [built]
[0]        [3] ./~/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 84 bytes {0} [built]
[0]        [4] ./~/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0 83 bytes {0} [built]
[0]        [5] ./~/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0 82 bytes {0} [built]
[0]        [6] ./~/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0 82 bytes {0} [built]
[0]        [7] ./~/css-loader!./~/less-loader!./~/font-awesome-webpack/font-awesome-styles.loader.js!./src/theme/font-awesome.config.prod.j                      s 39.3 kB {0} [built]
[0]        [9] ./~/less-loader/stringify.loader.js!./~/font-awesome/less/core.less 466 bytes [built]
[0]       [10] ./~/less-loader/stringify.loader.js!./~/font-awesome/less/icons.less 50.5 kB [built]
[0]       [11] ./~/less-loader/stringify.loader.js!./~/font-awesome/less/larger.less 385 bytes [built]
[0]       [12] ./~/less-loader/stringify.loader.js!./~/font-awesome/less/mixins.less 1.67 kB [built]
[0]       [13] ./~/less-loader/stringify.loader.js!./~/font-awesome/less/path.less 788 bytes [built]
[0]       [14] ./~/less-loader/stringify.loader.js!./~/font-awesome/less/variables.less 25.7 kB [built]
[0]       [15] ./~/less-loader/stringify.loader.js!./src/theme/font-awesome.config.less 121 bytes [built]
[0]         + 1 hidden modules
[0]
[0] npm
[0]  ERR! Windows_NT 10.0.14393
[0] npm ERR! argv
[0]  "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sylvain\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
[0] npm ERR! node v6.7.0
[0] npm ERR! npm  v3.10.8
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! react-redux-universal-hot-example@0.9.0 build: `better-npm-run build`
[0] npm ERR! Exit status 2
[0] npm ERR!
[0] npm ERR! Failed at the react-redux-universal-hot-example@0.9.0 build script 'better-npm-run build'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the react-redux-universal-hot-example package,
[0] npm ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     better-npm-run build
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs react-redux-universal-hot-example
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls react-redux-universal-hot-example
[0] npm ERR! There is likely additional logging output above.
[0]
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     C:\app\npm-debug.log
[0] npm run build exited with code 1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os"                      :"win32","arch":"x64"})
npm WARN multireducer@3.1.0 requires a peer of immutable@^3.0.0 but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sylvain\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-redux-universal-hot-example@0.9.0 postinstall: `concurrently "npm run build" "npm run build-dlls"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-universal-hot-example@0.9.0 postinstall script 'concurrently "npm run build" "npm run build-dlls"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-universal-hot-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run build" "npm run build-dlls"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-universal-hot-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-universal-hot-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\app\npm-debug.log

**Comment by sylc** [comment]
Please disregard, it was an error from me.
